(import (scheme) (chicken base) (chicken format) th)

(define (near? a b) (< (abs (- a b)) 1e-3))
(define (expect-success who thunk)
  (thunk))
(define (expect-error who thunk)
  (let ((ok (condition-case (begin (thunk) #f)
              (e () #t))))
    (assert ok (who "should have raised")))
  who)

;;; --- float tensor construction / access ---------------------------
(define t (make-float-tensor '(2 3)))
(assert (equal? (float-tensor-dims t) '(2 3)))
(assert (= (float-tensor-numel t) 6))
(assert (float-tensor-contiguous? t))

(for-each (lambda (ix) (apply float-tensor-set! t (cons 0.0 ix)))
          '((0 0) (0 1) (0 2) (1 0) (1 1) (1 2)))
(float-tensor-fill! t 0.0)
(float-tensor-set2d! t 0 0 1.0)
(float-tensor-set2d! t 0 1 2.0)
(float-tensor-set2d! t 0 2 9.5)
(float-tensor-set2d! t 1 0 4.0)
(float-tensor-set2d! t 1 1 5.0)
(float-tensor-set2d! t 1 2 6.0)
(assert (near? (float-tensor-get2d t 1 2) 6.0))
(assert (near? (float-tensor-ref t 1 1) 5.0))
(float-tensor-set! t 9.5 0 2)
(assert (near? (float-tensor-ref t 0 2) 9.5))
(assert (equal? (float-tensor->list t) '(1.0 2.0 9.5 4.0 5.0 6.0)))

;;; --- elementwise / reduction ops ----------------------------------
(float-tensor-add! t 1.0)                       ; [2 3 10.5 5 6 7]
(assert (near? (float-tensor-sum t) 33.5))
(float-tensor-mul! t 2.0)                       ; [4 6 21 10 12 14]
(assert (near? (float-tensor-sum t) 67.0))
(assert (near? (float-tensor-mean t) (/ 67.0 6)))
(assert (near? (float-tensor-min t) 4.0))
(assert (near? (float-tensor-max t) 21.0))
(float-tensor-pow! t 2.0)                       ; squares

;;; --- 1-D fast paths ------------------------------------------------
(define v (make-float-tensor '(4)))
(for-each (lambda (i) (float-tensor-set1d! v i (+ 1 (* i 1.0)))) '(0 1 2 3))
(assert (near? (float-tensor-get1d v 2) 3.0))
(assert (near? (float-tensor-sum v) 10.0))
(assert (near? (float-tensor-dot v v) 30.0))

;;; --- dangerously wrong usage raises scheme errors, not process exit
(expect-error 'rank-check (lambda () (float-tensor-set1d! t 0 1.0)))
(expect-error 'bounds-check (lambda () (float-tensor-get2d t 5 5)))
(expect-error 'indices-check (lambda () (float-tensor-ref t 0)))

;;; --- matrix multiply ----------------------------------------------
(define a (list->float-tensor '(2 2) '(1.0 2.0 3.0 4.0)))
(define b (list->float-tensor '(2 2) '(5.0 6.0 7.0 8.0)))
(define m (float-tensor-mm a b))
(assert (near? (float-tensor-get2d m 0 0) 19.0))
(assert (near? (float-tensor-get2d m 0 1) 22.0))
(assert (near? (float-tensor-get2d m 1 0) 43.0))
(assert (near? (float-tensor-get2d m 1 1) 50.0))

;;; --- copy / clone -------------------------------------------------
(define c (float-tensor-clone a))
(float-tensor-copy! c b)
(assert (near? (float-tensor-get2d c 0 0) 5.0))

;;; --- double tensor ------------------------------------------------
(define dd (make-double-tensor '(3)))
(define g (make-generator))
(assert (generator-valid? g))
(double-tensor-fill! dd 2.5)
(assert (near? (double-tensor-sum dd) 7.5))
(assert (near? (double-tensor-ref dd 2) 2.5))

(define (close? a b) (< (abs (- a b)) 0.02))
(define ds (make-double-tensor '(10000)))
(double-tensor-normal! ds g 3.0 0.5)
(assert (close? (double-tensor-mean ds) 3.0))
(assert (close? (double-tensor-var ds 1) 0.25))

;;; --- deterministic seeding ----------------------------------------
(generator-manual-seed! g 42)
(define r1 (generator-uniform g 0.0 1.0))
(generator-manual-seed! g 42)
(define r2 (generator-uniform g 0.0 1.0))
(assert (near? r1 r2))
(assert (>= (generator-initial-seed g) 0))

;;; --- random tensor fills ------------------------------------------
(define r (make-float-tensor '(1000)))
(generator-manual-seed! g 42)
(float-tensor-uniform! r g 0.0 1.0)
(define rl (float-tensor->list r))
(assert (>= (apply min rl) 0.0))
(assert (< (apply max rl) 1.0))
(generator-manual-seed! g 42)
(float-tensor-uniform! r g 0.0 1.0)
(assert (equal? rl (float-tensor->list r)))

;;; --- list roundtrip -----------------------------------------------
(define rd (list->double-tensor '(2 2) '(1.0 2.0 3.0 4.0)))
(assert (equal? (double-tensor->list rd) '(1.0 2.0 3.0 4.0)))

;;; --- integer tensor types (byte/char/short/int/long) ---------------
(for-each
 (lambda (k)
   (let ((m  (case k ((byte) make-byte-tensor) ((char) make-char-tensor)
                   ((short) make-short-tensor) ((int) make-int-tensor)
                   ((long) make-long-tensor)))
         (s! (case k ((byte) byte-tensor-set!) ((char) char-tensor-set!)
                   ((short) short-tensor-set!) ((int) int-tensor-set!)
                   ((long) long-tensor-set!)))
         (g! (case k ((byte) byte-tensor-get2d) ((char) char-tensor-get2d)
                   ((short) short-tensor-get2d) ((int) int-tensor-get2d)
                   ((long) long-tensor-get2d)))
         (fl (case k ((byte) byte-tensor-fill!) ((char) char-tensor-fill!)
                   ((short) short-tensor-fill!) ((int) int-tensor-fill!)
                   ((long) long-tensor-fill!)))
         (->l (case k ((byte) byte-tensor->list) ((char) char-tensor->list)
                    ((short) short-tensor->list) ((int) int-tensor->list)
                    ((long) long-tensor->list)))
         (sum (case k ((byte) byte-tensor-sum) ((char) char-tensor-sum)
                    ((short) short-tensor-sum) ((int) int-tensor-sum)
                    ((long) long-tensor-sum)))
         (min (case k ((byte) byte-tensor-min) ((char) char-tensor-min)
                    ((short) short-tensor-min) ((int) int-tensor-min)
                    ((long) long-tensor-min)))
         (max (case k ((byte) byte-tensor-max) ((char) char-tensor-max)
                    ((short) short-tensor-max) ((int) int-tensor-max)
                    ((long) long-tensor-max)))
         (med (case k ((byte) byte-tensor-median) ((char) char-tensor-median)
                    ((short) short-tensor-median) ((int) int-tensor-median)
                    ((long) long-tensor-median)))
         (dot (case k ((byte) byte-tensor-dot) ((char) char-tensor-dot)
                    ((short) short-tensor-dot) ((int) int-tensor-dot)
                    ((long) long-tensor-dot)))
         (add (case k ((byte) byte-tensor-add!) ((char) char-tensor-add!)
                    ((short) short-tensor-add!) ((int) int-tensor-add!)
                    ((long) long-tensor-add!)))
         (copy (case k ((byte) byte-tensor-copy!) ((char) char-tensor-copy!)
                     ((short) short-tensor-copy!) ((int) int-tensor-copy!)
                     ((long) long-tensor-copy!)))
         (ctr (case k ((byte) byte-tensor-mm) ((char) char-tensor-mm)
                    ((short) short-tensor-mm) ((int) int-tensor-mm)
                    ((long) long-tensor-mm)))
         (lt  (case k ((byte) list->byte-tensor) ((char) list->char-tensor)
                    ((short) list->short-tensor) ((int) list->int-tensor)
                    ((long) list->long-tensor)))
         (mk  (case k ((byte) make-byte-tensor) ((char) make-char-tensor)
                    ((short) make-short-tensor) ((int) make-int-tensor)
                    ((long) make-long-tensor))))
     (define t (m '(2 3)))
     (assert (equal? ((case k ((byte) byte-tensor-dims) ((char) char-tensor-dims)
                             ((short) short-tensor-dims) ((int) int-tensor-dims)
                             ((long) long-tensor-dims)) t) '(2 3)))
     (assert (= ((case k ((byte) byte-tensor-numel) ((char) char-tensor-numel)
                        ((short) short-tensor-numel) ((int) int-tensor-numel)
                        ((long) long-tensor-numel)) t) 6))
     (fl t 2)
     (s! t 9 1 2)
     (assert (= (g! t 1 2) 9))
     (assert (equal? (->l t) '(2 2 2 2 2 9)))
     (add t 1)
     (assert (= (sum t) 25))
     (assert (= (min t) 3))
     (assert (= (max t) 10))
     (assert (= (med t) 3))
     (define v (mk '(3)))
     (fl v 2)
     (s! v 3 2)
     (assert (= (dot v v) (+ 4 9 4)))
     (define mm (ctr (lt '(1 3) '(1 2 3)) (lt '(3 1) '(4 5 6))))
     (assert (equal? (->l mm) '(32)))
     (define src (lt '(2 3) '(7 8 9 10 11 12)))
     (copy t src)
     (assert (equal? (->l t) '(7 8 9 10 11 12)))))
  '(byte char short int long))

;;; --- integer abs (short/int/long only) -----------------------------
(define sa (make-short-tensor '(3)))
(short-tensor-fill! sa -3)
(short-tensor-abs! sa)
(assert (equal? (short-tensor->list sa) '(3 3 3)))
(define ia (make-int-tensor '(2)))
(int-tensor-fill! ia -7)
(int-tensor-abs! ia)
(assert (equal? (int-tensor->list ia) '(7 7)))
(define la (make-long-tensor '(2)))
(long-tensor-fill! la -1)
(long-tensor-abs! la)
(assert (equal? (long-tensor->list la) '(1 1)))

;;; --- integer random fills ------------------------------------------
(define ig (make-generator))
(define ib (make-byte-tensor '(5000)))
(generator-manual-seed! ig 7)
(byte-tensor-bernoulli! ib ig 0.5)
(define ibs (byte-tensor->list ib))
(assert (= (apply min ibs) 0))
(assert (= (apply max ibs) 1))
(generator-manual-seed! ig 7)
(byte-tensor-bernoulli! ib ig 0.5)
(assert (equal? ibs (byte-tensor->list ib)))
(define ip (make-long-tensor '(200)))
(long-tensor-poisson! ip ig 2.0)
;;; --- printing (numpy / torch format) --------------------------------
(define np-2d (list->float-tensor '(2 3) '(1.0 2.0 3.0 4.0 5.0 6.0)))
(assert (equal? (tensor->string np-2d) "[[1., 2., 3.],\n [4., 5., 6.]]"))
(assert (tensor? np-2d))
(define np-3d (list->float-tensor '(2 2 1) '(1.0 2.0 3.0 4.0)))
(assert (equal? (tensor->string np-3d) "[[[1.],\n  [2.]],\n [[3.],\n  [4.]]]"))
(define np-1d (list->float-tensor '(4) '(1.0 2.0 3.0 4.0)))
(assert (equal? (tensor->string np-1d) "[1., 2., 3., 4.]"))
(define np-int (list->int-tensor '(2 2) '(1 2 3 4)))
(assert (equal? (tensor->string np-int) "[[1, 2],\n [3, 4]]"))
(define np-byte (list->byte-tensor '(2 1) '(250 1)))
(assert (equal? (tensor->string np-byte) "[[250],\n [1]]"))
(define np-empty (make-float-tensor '(0)))
(assert (equal? (tensor->string np-empty) "[]"))
(write np-2d) (newline)

(print "th tests passed")